export const Flags = {
  en: { flag: "🇬🇧", language: "English", speechRecognitionLocale: "en-US" }, // You can change this to en-GB, en-AU, etc.
  tr: { flag: "🇹🇷", language: "Turkish", speechRecognitionLocale: "tr-TR" },
  it: { flag: "🇮🇹", language: "Italian", speechRecognitionLocale: "it-IT" },
  fr: { flag: "🇫🇷", language: "French", speechRecognitionLocale: "fr-FR" },
  ru: { flag: "🇷🇺", language: "Russian", speechRecognitionLocale: "ru-RU" },
  de: { flag: "🇩🇪", language: "German", speechRecognitionLocale: "de-DE" },
  es: { flag: "🇪🇸", language: "Spanish", speechRecognitionLocale: "es-ES" },
  ja: { flag: "🇯🇵", language: "Japanese", speechRecognitionLocale: "ja-JP" },
  ko: { flag: "🇰🇷", language: "Korean", speechRecognitionLocale: "ko-KR" },
  sv: { flag: "🇸🇪", language: "Swedish", speechRecognitionLocale: "sv-SE" },
  no: { flag: "🇳🇴", language: "Norwegian", speechRecognitionLocale: "no-NO" },
  fi: { flag: "🇫🇮", language: "Finnish", speechRecognitionLocale: "fi-FI" },
  el: { flag: "🇬🇷", language: "Greek", speechRecognitionLocale: "el-GR" },
  nl: { flag: "🇳🇱", language: "Dutch", speechRecognitionLocale: "nl-NL" },
  af: { flag: "🇿🇦", language: "Afrikaans", speechRecognitionLocale: "af-ZA" },
  sq: { flag: "🇦🇱", language: "Albanian", speechRecognitionLocale: "sq-AL" },
  am: { flag: "🇪🇹", language: "Amharic", speechRecognitionLocale: "am-ET" },
  ar: { flag: "🇸🇦", language: "Arabic", speechRecognitionLocale: "ar-SA" },
  hy: { flag: "🇦🇲", language: "Armenian", speechRecognitionLocale: "hy-AM" },
  az: { flag: "🇦🇿", language: "Azerbaijani", speechRecognitionLocale: "az-AZ" },
  eu: { flag: "🇪🇸", language: "Basque", speechRecognitionLocale: "eu-ES" },
  be: { flag: "🇧🇾", language: "Belarusian", speechRecognitionLocale: "be-BY" },
  bn: { flag: "🇧🇩", language: "Bengali", speechRecognitionLocale: "bn-BD" },
  bs: { flag: "🇧🇦", language: "Bosnian", speechRecognitionLocale: "bs-BA" },
  bg: { flag: "🇧🇬", language: "Bulgarian", speechRecognitionLocale: "bg-BG" },
  ca: { flag: "🇪🇸", language: "Catalan", speechRecognitionLocale: "ca-ES" },
  ceb: { flag: "🇵🇭", language: "Cebuano", speechRecognitionLocale: "ceb-PH" },
  ny: { flag: "🇲🇼", language: "Chichewa", speechRecognitionLocale: "ny-MW" },
  co: { flag: "🇫🇷", language: "Corsican", speechRecognitionLocale: "co-FR" },
  hr: { flag: "🇭🇷", language: "Croatian", speechRecognitionLocale: "hr-HR" },
  cs: { flag: "🇨🇿", language: "Czech", speechRecognitionLocale: "cs-CZ" },
  da: { flag: "🇩🇰", language: "Danish", speechRecognitionLocale: "da-DK" },
  eo: { flag: "🌐", language: "Esperanto", speechRecognitionLocale: "eo" },
  et: { flag: "🇪🇪", language: "Estonian", speechRecognitionLocale: "et-EE" },
  tl: { flag: "🇵🇭", language: "Filipino", speechRecognitionLocale: "tl-PH" },
  fy: { flag: "🇳🇱", language: "Frisian", speechRecognitionLocale: "fy-NL" },
  gl: { flag: "🇪🇸", language: "Galician", speechRecognitionLocale: "gl-ES" },
  ka: { flag: "🇬🇪", language: "Georgian", speechRecognitionLocale: "ka-GE" },
  gu: { flag: "🇮🇳", language: "Gujarati", speechRecognitionLocale: "gu-IN" },
  ht: {
    flag: "🇭🇹",
    language: "Haitian Creole",
    speechRecognitionLocale: "ht-HT",
  },
  ha: { flag: "🇳🇬", language: "Hausa", speechRecognitionLocale: "ha-NG" },
  he: { flag: "🇮🇱", language: "Hebrew", speechRecognitionLocale: "he-IL" },
  hi: { flag: "🇮🇳", language: "Hindi", speechRecognitionLocale: "hi-IN" },
  hu: { flag: "🇭🇺", language: "Hungarian", speechRecognitionLocale: "hu-HU" },
  is: { flag: "🇮🇸", language: "Icelandic", speechRecognitionLocale: "is-IS" },
  ig: { flag: "🇳🇬", language: "Igbo", speechRecognitionLocale: "ig-NG" },
  id: { flag: "🇮🇩", language: "Indonesian", speechRecognitionLocale: "id-ID" },
  ga: { flag: "🇮🇪", language: "Irish", speechRecognitionLocale: "ga-IE" },
  jw: { flag: "🇮🇩", language: "Javanese", speechRecognitionLocale: "jw-ID" },
  kn: { flag: "🇮🇳", language: "Kannada", speechRecognitionLocale: "kn-IN" },
  kk: { flag: "🇰🇿", language: "Kazakh", speechRecognitionLocale: "kk-KZ" },
  km: { flag: "🇰🇭", language: "Khmer", speechRecognitionLocale: "km-KH" },
  ku: { flag: "🇮🇶", language: "Kurdish", speechRecognitionLocale: "ku-TR" },
  ky: { flag: "🇰🇬", language: "Kyrgyz", speechRecognitionLocale: "ky-KG" },
  lo: { flag: "🇱🇦", language: "Lao", speechRecognitionLocale: "lo-LA" },
  la: { flag: "🇻🇦", language: "Latin", speechRecognitionLocale: "la" },
  lv: { flag: "🇱🇻", language: "Latvian", speechRecognitionLocale: "lv-LV" },
  lt: { flag: "🇱🇹", language: "Lithuanian", speechRecognitionLocale: "lt-LT" },
  lb: {
    flag: "🇱🇺",
    language: "Luxembourgish",
    speechRecognitionLocale: "lb-LU",
  },
  mk: { flag: "🇲🇰", language: "Macedonian", speechRecognitionLocale: "mk-MK" },
  mg: { flag: "🇲🇬", language: "Malagasy", speechRecognitionLocale: "mg-MG" },
  ms: { flag: "🇲🇾", language: "Malay", speechRecognitionLocale: "ms-MY" },
  ml: { flag: "🇮🇳", language: "Malayalam", speechRecognitionLocale: "ml-IN" },
  mt: { flag: "🇲🇹", language: "Maltese", speechRecognitionLocale: "mt-MT" },
  mi: { flag: "🇳🇿", language: "Maori", speechRecognitionLocale: "mi-NZ" },
  mr: { flag: "🇮🇳", language: "Marathi", speechRecognitionLocale: "mr-IN" },
  mn: { flag: "🇲🇳", language: "Mongolian", speechRecognitionLocale: "mn-MN" },
  my: { flag: "🇲🇲", language: "Burmese", speechRecognitionLocale: "my-MM" },
  ne: { flag: "🇳🇵", language: "Nepali", speechRecognitionLocale: "ne-NP" },
  ps: { flag: "🇦🇫", language: "Pashto", speechRecognitionLocale: "ps-AF" },
  fa: { flag: "🇮🇷", language: "Persian", speechRecognitionLocale: "fa-IR" },
  pl: { flag: "🇵🇱", language: "Polish", speechRecognitionLocale: "pl-PL" },
  pt: { flag: "🇵🇹", language: "Portuguese", speechRecognitionLocale: "pt-PT" }, // Can also be "pt-BR" for Brazil
  pa: { flag: "🇮🇳", language: "Punjabi", speechRecognitionLocale: "pa-IN" },
  ro: { flag: "🇷🇴", language: "Romanian", speechRecognitionLocale: "ro-RO" },
  sm: { flag: "🇼🇸", language: "Samoan", speechRecognitionLocale: "sm-WS" },
  gd: {
    flag: "🏴",
    language: "Scots Gaelic",
    speechRecognitionLocale: "gd-GB",
  },
  sr: { flag: "🇷🇸", language: "Serbian", speechRecognitionLocale: "sr-RS" },
  st: { flag: "🇱🇸", language: "Sesotho", speechRecognitionLocale: "st-LS" },
  sn: { flag: "🇿🇼", language: "Shona", speechRecognitionLocale: "sn-ZW" },
  sd: { flag: "🇵🇰", language: "Sindhi", speechRecognitionLocale: "sd-PK" },
  si: { flag: "🇱🇰", language: "Sinhala", speechRecognitionLocale: "si-LK" },
  sk: { flag: "🇸🇰", language: "Slovak", speechRecognitionLocale: "sk-SK" },
  sl: { flag: "🇸🇮", language: "Slovenian", speechRecognitionLocale: "sl-SI" },
  so: { flag: "🇸🇴", language: "Somali", speechRecognitionLocale: "so-SO" },
  su: { flag: "🇮🇩", language: "Sundanese", speechRecognitionLocale: "su-ID" },
  sw: { flag: "🇹🇿", language: "Swahili", speechRecognitionLocale: "sw-TZ" },
  tg: { flag: "🇹🇯", language: "Tajik", speechRecognitionLocale: "tg-TJ" },
  ta: { flag: "🇮🇳", language: "Tamil", speechRecognitionLocale: "ta-IN" },
  te: { flag: "🇮🇳", language: "Telugu", speechRecognitionLocale: "te-IN" },
  th: { flag: "🇹🇭", language: "Thai", speechRecognitionLocale: "th-TH" },
  uk: { flag: "🇺🇦", language: "Ukrainian", speechRecognitionLocale: "uk-UA" },
  ur: { flag: "🇵🇰", language: "Urdu", speechRecognitionLocale: "ur-PK" },
  ug: { flag: "🇨🇳", language: "Uyghur", speechRecognitionLocale: "ug-CN" },
  uz: { flag: "🇺🇿", language: "Uzbek", speechRecognitionLocale: "uz-UZ" },
  vi: { flag: "🇻🇳", language: "Vietnamese", speechRecognitionLocale: "vi-VN" },
  cy: { flag: "🏴", language: "Welsh", speechRecognitionLocale: "cy-GB" },
  xh: { flag: "🇿🇦", language: "Xhosa", speechRecognitionLocale: "xh-ZA" },
  yi: { flag: "🇮🇱", language: "Yiddish", speechRecognitionLocale: "yi" },
  yo: { flag: "🇳🇬", language: "Yoruba", speechRecognitionLocale: "yo-NG" },
  zu: { flag: "🇿🇦", language: "Zulu", speechRecognitionLocale: "zu-ZA" },
};
